import { createEnv } from "@t3-oss/env-nextjs"
import { z } from "zod"

export const env = createEnv({
	server: {
		CONVEX_DEPLOY_KEY: z.string().min(1),
		CONVEX_DEPLOYMENT_ID: z.string().min(1),
		AUTH_GITHUB_ID: z.string().min(1),
		AUTH_GITHUB_SECRET: z.string().min(1),
		AUTH_GOOGLE_ID: z.string().min(1),
		AUTH_GOOGLE_SECRET: z.string().min(1),
		AUTH_DISCORD_ID: z.string().min(1),
		AUTH_DISCORD_SECRET: z.string().min(1),
		AUTH_DISCORD_APPLICATION_ID: z.string().min(1),
		AUTH_DISCORD_PUBLIC_KEY: z.string().min(1),
		EMAIL_FROM: z.string().min(1),
		EMAIL_SERVER_USER: z.string().min(1),
		EMAIL_SERVER_HOST: z.string().min(1),
		EMAIL_SERVER_PORT: z.string().min(1),
		EMAIL_SERVER_PASSWORD: z.string().min(1),
		RESEND_AUDIENCE_ID: z.string().min(1),
	},
	client: {
	NEXT_PUBLIC_POSTHOG_KEY: z.string().min(1),
	NEXT_PUBLIC_POSTHOG_HOST: z.string().min(1),
	NEXT_PUBLIC_CONVEX_URL: z.string().min(1),
	},
	runtimeEnv: {
		CONVEX_DEPLOY_KEY: process.env.CONVEX_DEPLOY_KEY,
		CONVEX_DEPLOYMENT_ID: process.env.CONVEX_DEPLOYMENT_ID,
		AUTH_GITHUB_ID: process.env.AUTH_GITHUB_ID,
		AUTH_GITHUB_SECRET: process.env.AUTH_GITHUB_SECRET,
		AUTH_GOOGLE_ID: process.env.AUTH_GOOGLE_ID,
		AUTH_GOOGLE_SECRET: process.env.AUTH_GOOGLE_SECRET,
		AUTH_DISCORD_ID: process.env.AUTH_DISCORD_ID,
		AUTH_DISCORD_SECRET: process.env.AUTH_DISCORD_SECRET,
		AUTH_DISCORD_APPLICATION_ID: process.env.AUTH_DISCORD_APPLICATION_ID,
		AUTH_DISCORD_PUBLIC_KEY: process.env.AUTH_DISCORD_PUBLIC_KEY,
		EMAIL_FROM: process.env.EMAIL_FROM,
		EMAIL_SERVER_USER: process.env.EMAIL_SERVER_USER,
		EMAIL_SERVER_HOST: process.env.EMAIL_SERVER_HOST,
		EMAIL_SERVER_PORT: process.env.EMAIL_SERVER_PORT,
		EMAIL_SERVER_PASSWORD: process.env.EMAIL_SERVER_PASSWORD,
		RESEND_AUDIENCE_ID: process.env.RESEND_AUDIENCE_ID,
		NEXT_PUBLIC_POSTHOG_KEY: process.env.NEXT_PUBLIC_POSTHOG_KEY,
		NEXT_PUBLIC_POSTHOG_HOST: process.env.NEXT_PUBLIC_POSTHOG_HOST,
		NEXT_PUBLIC_CONVEX_URL: process.env.NEXT_PUBLIC_CONVEX_URL,
	},
})
